
###
POST http://localhost:8080/relations/task1
Content-Type: application/json

{
  "w1": "t1",
  "w2": "r",
  "r": "ANTONYM"
}
###
POST http://localhost:8080/relations/task1
Content-Type: application/json

{
  "w1": "smth",
  "w2": "smth2",
  "r": "RELATED"
}
###

GET http://localhost:8080/relations/inverse
